CREATE USER Blazkowicz WITH PASSWORD 'William1939';

REVOKE ALL ON ALL TABLES IN SCHEMA public FROM Blazkowicz;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM Blazkowicz;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA public FROM Blazkowicz;

GRANT CONNECT ON DATABASE banking_system TO Blazkowicz;
GRANT USAGE ON SCHEMA public TO Blazkowicz;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO Blazkowicz;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT ON TABLES TO Blazkowicz;

REVOKE INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER
ON ALL TABLES IN SCHEMA public FROM Blazkowicz;

-- \du Blazkowicz
-- \z