services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: neda.z
      POSTGRES_PASSWORD: nz2003nz
      POSTGRES_DB: banking_system
    ports:
      - "5433:5432"
    volumes:
      - ./tables.sql:/docker-entrypoint-initdb.d/tables.sql
      - postgres-data:/var/lib/postgresql/data
    networks:
      - db_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U neda.z -d banking_system"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  app:
    build: .
    container_name: app
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: neda.z
      DB_PASSWORD: nz2003nz
      DB_NAME: banking_system
    ports:
      - "8080:8080"
    networks:
      - db_network
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres-data:
    driver: local

networks:
  db_network:
