version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: neda.z
      POSTGRES_PASSWORD: nz2003nz
      POSTGRES_DB: banking_system
    ports:
      - "5432:5432"
    volumes:
      - ./tables.sql:/docker-entrypoint-initdb.d/tables.sql
      - postgres-data:/var/lib/postgresql/dat

  app:
    build: .
    container_name: app
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: neda.z
      DB_PASSWORD: nz2003nz
      DB_NAME: banking_system
    ports:
      - "8080:8080" 

volumes:
  postgres-data: